accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import signup


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="home")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryListView,
    AccountListView,
    ExpenseCategoryCreateView,
    AccountCreateView,
)


urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path(
        "categories/", ExpenseCategoryListView.as_view(), name="list_category"
    ),
    path("accounts/", AccountListView.as_view(), name="list_account"),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/",
        AccountCreateView.as_view(),
        name="create_account",
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.forms import CharField
from django.contrib.auth.models import User


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        User, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account, related_name="receipts", on_delete=models.CASCADE
    )

accounts/views.py
# from django.shortcuts import render

# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
# from django.contrib import messages
# from django.shortcuts import redirect


# def register(request):
#     if request.method == "POST":
#         f = UserCreationForm(request.POST)
#         if f.is_valid():
#             f.save()
#             messages.success(request, "Account created successfully")
#             return redirect("register")
#     else:
#         f = UserCreationForm()
#     return render(request, "cadmin/register.html", {"form": f})

# Above is how far I got with this part before checking to see the answer. I'm not sure how I would've gotten without looking at the solution.

from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from receipts.models import Account, ExpenseCategory, Receipt
from django.contrib.auth.mixins import LoginRequiredMixin


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipt_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["purchaser"] = self.request.user
        return context

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "create_receipt.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "category_list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "account_list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "create_category.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_category")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "create_account.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_account")


#

receipts/templates/account_list.html
{% extends 'base.html' %}

{% block content %}
  <main>
        <h1>My Accounts</h1>
        <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of receipts</th>
              </tr>
            </thead>
            <tbody>
              {% for account in account_list %}
                <tr>
                  <td>{{account.name}}</td>
                  <td>{{account.number}}</td>
                  <td>{{account.receipts.all | length }}</td>
                </tr>
            </tbody>
            {% endfor %}
          </table>
  </main>
  {% endblock content %}

receipts/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Expenses: the Web App!</title>
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
  <header>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'logout' %}">Logout</a>
        </li>
        {% endif %}
        {% if user.is_authenticated == False %}
        <li>
          <a href="{% url 'signup' %}">Signup</a>
          <a href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'list_category' %}">Categories List</a></li>
        <li><a href="{% url 'list_account' %}">Accounts List</a></li>
        <li><a href="{% url 'create_receipt' %}">Create Receipt</a></li>
        <li><a href="{% url 'create_category' %}">Create Category</a></li>
        <li><a href="{% url 'create_account' %}">Create Account</a></li>

      </ul>
    </nav>
    {% block pagination %}
    {% endblock pagination %}
  </header>
  {% block content %}
  {% endblock content %}
</body>

</html>


<li><a href="{% url 'create_category' %}">Create category</a></li>

receipts/templates/category_list.html
{% extends 'base.html' %}

{% block content %}
  <main>
        <h1>My Categories</h1>
        <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Number of receipts</th>
              </tr>
            </thead>
            <tbody>
              {% for category in expensecategory_list %}
                <tr>
                  <td>{{category.name}}</td>
                  <td>{{category.receipts.all | length }}</td>
                
                </tr>
            </tbody>
            {% endfor %}
          </table>
  </main>
  {% endblock content %}

receipts/templates/create_account.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div> 
        <h1>Create Account</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form> 
            
    </div>
</main>



{% endblock content %}

receipts/templates/create_category.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div> 
        <h1>Create Category</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form> 
            
    </div>
</main>



{% endblock content %}

receipts/templates/create_receipt.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div> 
        <h1>Create Receipt</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form> 
            
    </div>
</main>



{% endblock content %}

receipts/templates/receipt_list.html
{% extends 'base.html' %}

{% block content %}
  <main>
        <h1>My Receipts</h1>
        <table>
            <thead>
              <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
              </tr>
            </thead>
            <tbody>
              {% for receipt in receipt_list %}
                <tr>
                  <td>{{receipt.vendor}}</td>
                  <td>{{receipt.total}}</td>
                  <td>{{receipt.tax}}</td>
                  <td>{{receipt.date|date:'m/d/Y'}}</td>
                  <td>{{receipt.category}}</td>
                  <td>{{receipt.account}}</td>
                </tr>
            </tbody>
            {% endfor %}
          </table>
  </main>
  {% endblock content %}